/**
 * ESHC Api's
 * ESHC APIs exposed from a Java EE back-end to an Angular front-end
 *
 * OpenAPI spec version: V1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export class ActionPoint {
    category?: string;
    created?: Date;
    currentStatus?: ActionPoint.CurrentStatusEnum;
    description?: string;
    id: number;
    lastModified?: Date;
    leadContributor?: number;
    listOfContributors?: Array<number>;
    listOfNotes?: Array<number>;
    listOfWatchers?: Array<number>;
    tasks?: Array<number>;
    title?: string;
    version?: number;
}
export namespace ActionPoint {
    export type CurrentStatusEnum = 'UNSTARTED' | 'STARTED' | 'FINISHED';
    export const CurrentStatusEnum = {
        UNSTARTED: 'UNSTARTED' as CurrentStatusEnum,
        STARTED: 'STARTED' as CurrentStatusEnum,
        FINISHED: 'FINISHED' as CurrentStatusEnum
    }
}
