/**
 * ESHC Api's
 * ESHC APIs exposed from a Java EE back-end to an Angular front-end
 *
 * OpenAPI spec version: V1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Task {
    dateTimeCreated?: Date;
    description?: string;
    id?: number;
    leadContributor?: number;
    listOfContributors?: Array<number>;
    notes?: Array<number>;
}
